name: Deploy to Server

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /root/food_quality_control || git clone git@github.com:MrFedko/food_quality_control.git /root/food_quality_control
            cd /root/food_quality_control
            git pull origin main
            source .venv/bin/activate
            pip install -r requirements.txt
            systemctl restart mybot.service
